sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t anvimal/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true anvimal/docker-react npm run test -- --coverage